# Generated by Django 5.2.7 on 2025-11-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_ratings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recommended_percent',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='product',
            name='total_review',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
