# Generated by Django 5.2.7 on 2025-11-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_recommended_percent_product_total_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='recommended_percent',
            new_name='recommended_percentage',
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
