# Generated by Django 5.2.7 on 2025-11-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_recommended_percent_product_recommended_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='recommended_percentage',
            field=models.FloatField(default=100.0, null=True),
        ),
    ]
