# Generated by Django 5.2.7 on 2025-11-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
