# Generated by Django 5.2.7 on 2025-12-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0003_alter_customuser_email_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(choices=[('UK', 'United Kingdom'), ('BD', 'Bangladesh'), ('IN', 'India'), ('PK', 'Pakistan'), ('FR', 'France')], default='BD', max_length=10),
        ),
    ]
