# Generated by Django 5.2.7 on 2025-11-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreviews',
            name='rating',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='productreviews',
            name='recommended_percent',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='productreviews',
            name='total_review',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
