# Generated by Django 5.2.7 on 2025-11-09 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_productreviews_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreviews',
            name='recommended_percent',
        ),
        migrations.RemoveField(
            model_name='productreviews',
            name='total_review',
        ),
    ]
