# Generated by Django 5.2.7 on 2025-11-09 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_recommended_percent_product_recommended_percentage_and_more'),
        ('review', '0003_remove_productreviews_recommended_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviews',
            name='review_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='productreviews',
            unique_together={('product', 'user')},
        ),
    ]
